waypoints:
- id: 0
  pose: [0.0, 0.00, 0.0]
  to: [1]
- id: 1
  pose: [0.98, 0.00, 0.0]
  to: [2,0,4]
- id: 2
  pose: [0.98, 1.1, -0.04]
  to: [3,1]
- id: 3
  pose: [0.98, 2.3, -0.05]
  to: [2]
- id: 4
  pose: [0.98, -0.8, -1.57]
  to: [1,5]
- id: 5
  pose: [0.98, -1.85, -1.5]
  to: [4]
