map_name: map_01
use_teb: true
map_frame: map

mapping:
  map_name: map_01
  map_topic: /map
  scan_topic: /scan
  save_path: /home/ubuntu/ros2_ws/src/slam/maps/map_01
  status_period_sec: 5.0
  save_timeout_sec: 15.0

navigation:
  timeout_sec: 600.0
  feedback_period_sec: 5.0
  stop_topics:
    - /controller/cmd_vel
    - /cmd_vel

qrcode:
  image_topic: /depth_cam/rgb0/image_raw
  target_topic: /qrcode/target
  image_result_topic: /qrcode/image_result
  detection_period_sec: 0.2
  timeout_sec: 0.0
  allowed_targets:
    - pick_area
    - goal_red
    - goal_green
    - goal_blue

waypoints:
  home:
    x: 0.0
    y: 0.0
    yaw_deg: 0.0
  pick_area:
    x: 1.0
    y: 0.0
    yaw_deg: 0.0
  goal_red:
    x: 1.0
    y: 1.0
    yaw_deg: 90.0
  goal_green:
    x: 0.0
    y: 1.0
    yaw_deg: 180.0
  goal_blue:
    x: -1.0
    y: 1.0
    yaw_deg: 180.0

behavior:
  require_initial_pose: true
  initial_pose_topic: /initialpose
  start_topic: /behavior_start
  reset_topic: /behavior_reset
  default_task: qrcode_target   #patrol, qrcode_target
  patrol_points:
    - pick_area
    - home
  patrol_count: 3

transport:
  target_color: red
  goal_by_color:
    red: goal_red
    green: goal_green
    blue: goal_blue
  require_initial_pose: true
  initial_pose_topic: /initialpose
  start_topic: /transport_start
  cancel_topic: /transport_cancel
  state_topic: /transport_workflow/state
  service_timeout_sec: 30.0
  pick_place_node: /pick_place_node

vision:
  detect_type: rect
  target_pixel:
    x: 330
    y: 260
  x_tolerance_px: 10
  y_tolerance_px: 10
  stable_frames: 10
  angular_gain: 0.003
  linear_gain: 0.0028
  max_angular_speed: 0.12
  max_linear_speed: 0.03
  control_period_sec: 0.1
  detection_timeout_sec: 15.0
  lost_timeout_sec: 2.0

arm:
  action_group_dir: /home/ubuntu/software/arm_pc/ActionGroups
  pick_ready_action: navigation_pick_init
  pick_action: navigation_pick
  place_action: navigation_place
  safe_action: navigation_pick_init
  pick_ready_timeout_sec: 15.0
  pick_timeout_sec: 20.0
  place_timeout_sec: 20.0
  safe_timeout_sec: 15.0
